Added dependency check

diff --git a/yt-search-play b/yt-search-play
--- a/yt-search-play
+++ b/yt-search-play
@@ -1,5 +1,16 @@
 #!/bin/bash
 
+## Check dependencies
+
+check_failed=
+type rofi &>/dev/null || (>&2 echo "The dependency rofi is missing. See https://github.com/davatorium/rofi/blob/next/INSTALL.md for instructions on how to install it."; check_failed=true)
+type youtube-dl &>/dev/null || (>&2 echo "The dependency youtube-dl is missing. See https://github.com/ytdl-org/youtube-dl/blob/master/README.md#installation for instructions on how to install it."; check_failed=true)
+type mpv &>/dev/null || (>&2 echo "The dependency mpv is missing. See https://mpv.io/installation for instructions on how to install it."; check_failed=true)
+if [[ "$check_failed" ]]
+then
+	exit 1
+fi
+
 ## Where am I?
 
 script_path=$(realpath $0)
@@ -15,7 +26,7 @@ data_dir=".data"
 force_no_cache=
 subs_mode=
 
-## Rewrite_default_config
+## (Re)write default config
 
 jq -n --arg search_size "$search_size" --arg max_history_size "$max_history_size" --arg max_cache_age "$max_cache_age" --arg data_dir "$data_dir" --arg force_no_cache "$force_no_cache" --arg subs_mode "$subs_mode" '{search_size: $search_size, max_history_size: $max_history_size, max_cache_age: $max_cache_age, data_dir: $data_dir, force_no_cache: $force_no_cache, subs_mode: $subs_mode}' > "$default_configfile"
 
@@ -230,7 +241,7 @@ do_search () {
 	then
 		find_video "https://www.youtube.com/feed/subscriptions"
 	else
-		search_query=$(tac "$historyfile" | rofi -dmenu -p "Search YouTube" -theme-str 'entry { placeholder: "Enter text or select recent search..."; }' -l $([[ $history_size -lt 10 ]] && echo "$history_size" || echo 10) -scroll-method 0)
+		search_query=$(tac "$historyfile" | rofi -dmenu -p "Search YouTube" -no-show-icons -theme-str 'entry { placeholder: "Enter text or select recent search..."; }' -l $([[ $history_size -lt 10 ]] && echo "$history_size" || echo 10) -scroll-method 0)
 		if [[ "$search_query" =~ (https?\:\/\/)?(www\.)?(youtube\.com|youtu\.?be)\/.+$ ]]
 		then
 			selection="$search_query"
